:sparkles: Add function code
acesrg/identification_methods pull request #2
Opened 2020-06-25 22:38 UTC by ebernardi

Figure was added too.

2020-06-25 23:15 UTC, MarcoMiretti requested changes

2020-06-25 23:15 UTC, MarcoMiretti commented on identification_methods.m
> +function validate_identifications(data, Gzi, Gzi_mc, N)
En lugar de pasarle `N` que tal si solo le pasamos `data` y luego hacemos.

`N = size(data, 1);`

Nos ahorramos un argumento y lo hacemos menos propenso a errores (`N` diferente de el tamaño de `data`)

2020-06-25 23:15 UTC, MarcoMiretti commented on identification_methods.m
> +    t = (1:N);
Por otro lado, tal vez es mejor `data_size` en lugar de `N`

2020-06-25 23:17 UTC, ebernardi commented on identification_methods.m
> +function validate_identifications(data, Gzi, Gzi_mc, N)
Me parece muy bien...

2020-06-25 23:20 UTC, MarcoMiretti commented on identification_methods.m
> +    t = (1:N);
Esta la dejo a tu criterio :nail_care:

2020-06-25 23:25 UTC, ebernardi commented on identification_methods.m
> +    t = (1:N);
Fijate si te gusta ahora :kissing_heart:

2020-06-25 23:27 UTC, MarcoMiretti approved these changes

2020-07-02 21:30 UTC, paulaolmedo approved these changes

2020-07-02 21:31 UTC, merged